apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:/Users/Omkar/OneDrive/Desktop/Projects/Mongodb/mongodb-pv-path
  persistentVolumeReclaimPolicy: Retain
